2017-12-05T10:52:41.915+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2017-12-05T10:52:41.945+0000 I CONTROL  [initandlisten] MongoDB starting : pid=38 port=27018 dbpath=/data/27018/data 64-bit host=66d397fb1148
2017-12-05T10:52:41.946+0000 I CONTROL  [initandlisten] db version v3.4.10
2017-12-05T10:52:41.946+0000 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-05T10:52:41.946+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-12-05T10:52:41.946+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-05T10:52:41.947+0000 I CONTROL  [initandlisten] modules: none
2017-12-05T10:52:41.947+0000 I CONTROL  [initandlisten] build environment:
2017-12-05T10:52:41.947+0000 I CONTROL  [initandlisten]     distmod: rhel70
2017-12-05T10:52:41.947+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-05T10:52:41.948+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-05T10:52:41.948+0000 I CONTROL  [initandlisten] options: { config: "/conf/27018.conf", net: { http: { RESTInterfaceEnabled: true, enabled: true }, maxIncomingConnections: 300, port: 27018 }, processManagement: { fork: true, pidFilePath: "/data/27018/logs/mongod.pid" }, replication: { replSet: "rs" }, storage: { dbPath: "/data/27018/data" }, systemLog: { destination: "file", logAppend: true, path: "/data/27018/logs/mongod.log" } }
2017-12-05T10:52:41.952+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-05T11:01:28.684+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2017-12-05T11:01:28.711+0000 I CONTROL  [initandlisten] MongoDB starting : pid=40 port=27018 dbpath=/data/27018/data 64-bit host=c526be9fe055
2017-12-05T11:01:28.711+0000 I CONTROL  [initandlisten] db version v3.4.10
2017-12-05T11:01:28.712+0000 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-05T11:01:28.712+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-12-05T11:01:28.712+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-05T11:01:28.712+0000 I CONTROL  [initandlisten] modules: none
2017-12-05T11:01:28.713+0000 I CONTROL  [initandlisten] build environment:
2017-12-05T11:01:28.713+0000 I CONTROL  [initandlisten]     distmod: rhel70
2017-12-05T11:01:28.713+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-05T11:01:28.714+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-05T11:01:28.714+0000 I CONTROL  [initandlisten] options: { config: "/conf/27018.conf", net: { http: { enabled: false }, maxIncomingConnections: 300, port: 27018 }, processManagement: { fork: true, pidFilePath: "/data/27018/logs/mongod.pid" }, replication: { replSet: "rs" }, storage: { dbPath: "/data/27018/data" }, systemLog: { destination: "file", logAppend: true, path: "/data/27018/logs/mongod.log" } }
2017-12-05T11:01:28.717+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-05T11:01:34.996+0000 I CONTROL  [initandlisten] 
2017-12-05T11:01:34.996+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-05T11:01:34.997+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-05T11:01:34.997+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-05T11:01:34.997+0000 I CONTROL  [initandlisten] 
2017-12-05T11:01:35.010+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/27018/data/diagnostic.data'
2017-12-05T11:01:35.029+0000 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-05T11:01:35.030+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-05T11:01:35.032+0000 I NETWORK  [thread1] waiting for connections on port 27018
2017-12-05T11:03:10.084+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:53106 #1 (1 connection now open)
2017-12-05T11:03:10.087+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:53106 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:04:51.139+0000 I -        [conn1] end connection 127.0.0.1:53106 (1 connection now open)
2017-12-05T11:06:31.541+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:53108 #2 (1 connection now open)
2017-12-05T11:06:31.547+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:53108 conn2: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:06:31.549+0000 I REPL     [conn2] replSetInitiate admin command received from client
2017-12-05T11:06:31.549+0000 E REPL     [conn2] replSet initiate got NodeNotFound: No host described in new configuration 1 for replica set rs maps to this node while validating { _id: "rs", members: [ { _id: 0.0, host: "0.0.0.0:27018" }, { _id: 1.0, host: "0.0.0.0:27019" }, { _id: 2.0, host: "0.0.0.0:27020" } ], version: 1 }
2017-12-05T11:06:31.551+0000 I -        [conn2] end connection 127.0.0.1:53108 (1 connection now open)
2017-12-05T11:07:50.043+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:53110 #3 (1 connection now open)
2017-12-05T11:07:50.044+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:53110 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:09:30.724+0000 I -        [conn3] end connection 127.0.0.1:53110 (1 connection now open)
2017-12-05T11:11:28.419+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:53112 #4 (1 connection now open)
2017-12-05T11:11:28.425+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:53112 conn4: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:11:30.539+0000 I REPL     [conn4] replSetInitiate admin command received from client
2017-12-05T11:11:30.540+0000 E REPL     [conn4] replSet initiate got NodeNotFound: No host described in new configuration 1 for replica set rs maps to this node while validating { _id: "rs", members: [ { _id: 0.0, host: "0.0.0.0:27018" }, { _id: 1.0, host: "0.0.0.0:27019" }, { _id: 2.0, host: "0.0.0.0:27020" } ], version: 1 }
2017-12-05T11:13:28.172+0000 I COMMAND  [conn4] initiate : no configuration specified. Using a default configuration for the set
2017-12-05T11:13:28.178+0000 I COMMAND  [conn4] created this configuration for initiation : { _id: "rs", version: 1, members: [ { _id: 0, host: "c526be9fe055:27018" } ] }
2017-12-05T11:13:28.178+0000 I REPL     [conn4] replSetInitiate admin command received from client
2017-12-05T11:13:28.179+0000 I REPL     [conn4] replSetInitiate config object with 1 members parses ok
2017-12-05T11:13:28.180+0000 I REPL     [conn4] ******
2017-12-05T11:13:28.180+0000 I REPL     [conn4] creating replication oplog of size: 3180MB...
2017-12-05T11:13:28.184+0000 I STORAGE  [conn4] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-05T11:13:28.184+0000 I STORAGE  [conn4] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-05T11:13:28.184+0000 I STORAGE  [conn4] Scanning the oplog to determine where to place markers for truncation
2017-12-05T11:13:28.195+0000 I REPL     [conn4] ******
2017-12-05T11:13:28.222+0000 I INDEX    [conn4] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-05T11:13:28.222+0000 I INDEX    [conn4] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-05T11:13:28.224+0000 I INDEX    [conn4] build index done.  scanned 0 total records. 0 secs
2017-12-05T11:13:28.225+0000 I COMMAND  [conn4] setting featureCompatibilityVersion to 3.4
2017-12-05T11:13:28.226+0000 I REPL     [conn4] New replica set config in use: { _id: "rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "c526be9fe055:27018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a267f582897842bd42845cb') } }
2017-12-05T11:13:28.226+0000 I REPL     [conn4] This node is c526be9fe055:27018 in the config
2017-12-05T11:13:28.226+0000 I REPL     [conn4] transition to STARTUP2
2017-12-05T11:13:28.226+0000 I REPL     [conn4] Starting replication storage threads
2017-12-05T11:13:28.227+0000 I REPL     [conn4] Starting replication fetcher thread
2017-12-05T11:13:28.227+0000 I REPL     [conn4] Starting replication applier thread
2017-12-05T11:13:28.227+0000 I REPL     [conn4] Starting replication reporter thread
2017-12-05T11:13:28.228+0000 I REPL     [rsSync] transition to RECOVERING
2017-12-05T11:13:28.235+0000 I REPL     [rsSync] transition to SECONDARY
2017-12-05T11:13:28.236+0000 I REPL     [rsSync] conducting a dry run election to see if we could be elected
2017-12-05T11:13:28.237+0000 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-05T11:13:28.246+0000 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 1
2017-12-05T11:13:28.247+0000 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-05T11:13:28.247+0000 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-05T11:13:28.247+0000 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-05T11:13:30.239+0000 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-05T11:13:59.298+0000 I REPL     [conn4] replSetReconfig admin command received from client
2017-12-05T11:13:59.304+0000 I REPL     [conn4] replSetReconfig config object with 2 members parses ok
2017-12-05T11:13:59.304+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 0.0.0.0:27019
2017-12-05T11:13:59.306+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 0.0.0.0:27019, took 2ms (1 connections now open to 0.0.0.0:27019)
2017-12-05T11:13:59.307+0000 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "rs", version: 2, protocolVersion: 1, members: [ { _id: 0, host: "c526be9fe055:27018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "0.0.0.0:27019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a267f582897842bd42845cb') } }
2017-12-05T11:13:59.307+0000 I REPL     [ReplicationExecutor] This node is c526be9fe055:27018 in the config
2017-12-05T11:13:59.307+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38010 #5 (2 connections now open)
2017-12-05T11:13:59.308+0000 I REPL     [ReplicationExecutor] Member 0.0.0.0:27019 is now in state STARTUP
2017-12-05T11:13:59.308+0000 I NETWORK  [conn5] received client metadata from 172.17.0.3:38010 conn5: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:13:59.310+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38012 #6 (3 connections now open)
2017-12-05T11:13:59.311+0000 I -        [conn6] end connection 172.17.0.3:38012 (3 connections now open)
2017-12-05T11:14:01.311+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38014 #7 (3 connections now open)
2017-12-05T11:14:01.312+0000 I -        [conn7] end connection 172.17.0.3:38014 (3 connections now open)
2017-12-05T11:14:02.784+0000 I REPL     [conn4] replSetReconfig admin command received from client
2017-12-05T11:14:02.785+0000 I REPL     [conn4] replSetReconfig config object with 3 members parses ok
2017-12-05T11:14:02.785+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 0.0.0.0:27020
2017-12-05T11:14:02.787+0000 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "rs", version: 3, protocolVersion: 1, members: [ { _id: 0, host: "c526be9fe055:27018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "0.0.0.0:27019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "0.0.0.0:27020", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a267f582897842bd42845cb') } }
2017-12-05T11:14:02.787+0000 I REPL     [ReplicationExecutor] This node is c526be9fe055:27018 in the config
2017-12-05T11:14:02.788+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 0.0.0.0:27020
2017-12-05T11:14:02.793+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 0.0.0.0:27020, took 8ms (2 connections now open to 0.0.0.0:27020)
2017-12-05T11:14:02.793+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 0.0.0.0:27020, took 5ms (2 connections now open to 0.0.0.0:27020)
2017-12-05T11:14:02.794+0000 I REPL     [ReplicationExecutor] Member 0.0.0.0:27020 is now in state STARTUP
2017-12-05T11:14:02.795+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38020 #8 (3 connections now open)
2017-12-05T11:14:02.795+0000 I NETWORK  [conn8] received client metadata from 172.17.0.3:38020 conn8: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:14:02.796+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38022 #9 (4 connections now open)
2017-12-05T11:14:02.797+0000 I -        [conn9] end connection 172.17.0.3:38022 (4 connections now open)
2017-12-05T11:14:03.312+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38024 #10 (4 connections now open)
2017-12-05T11:14:03.313+0000 I -        [conn10] end connection 172.17.0.3:38024 (4 connections now open)
2017-12-05T11:14:04.797+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38026 #11 (4 connections now open)
2017-12-05T11:14:04.806+0000 I -        [conn11] end connection 172.17.0.3:38026 (4 connections now open)
2017-12-05T11:14:05.315+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38028 #12 (4 connections now open)
2017-12-05T11:14:05.317+0000 I -        [conn12] end connection 172.17.0.3:38028 (4 connections now open)
2017-12-05T11:14:06.798+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38030 #13 (4 connections now open)
2017-12-05T11:14:06.799+0000 I -        [conn13] end connection 172.17.0.3:38030 (4 connections now open)
2017-12-05T11:14:07.317+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38032 #14 (4 connections now open)
2017-12-05T11:14:07.318+0000 I -        [conn14] end connection 172.17.0.3:38032 (4 connections now open)
2017-12-05T11:14:08.800+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38034 #15 (4 connections now open)
2017-12-05T11:14:08.801+0000 I -        [conn15] end connection 172.17.0.3:38034 (4 connections now open)
2017-12-05T11:14:09.319+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38036 #16 (4 connections now open)
2017-12-05T11:14:09.320+0000 I -        [conn16] end connection 172.17.0.3:38036 (4 connections now open)
2017-12-05T11:14:10.801+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38038 #17 (4 connections now open)
2017-12-05T11:14:10.802+0000 I -        [conn17] end connection 172.17.0.3:38038 (4 connections now open)
2017-12-05T11:14:11.319+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38040 #18 (4 connections now open)
2017-12-05T11:14:11.320+0000 I -        [conn18] end connection 172.17.0.3:38040 (4 connections now open)
2017-12-05T11:14:12.788+0000 I REPL     [ReplicationExecutor] can't see a majority of the set, relinquishing primary
2017-12-05T11:14:12.789+0000 I REPL     [ReplicationExecutor] Stepping down from primary in response to heartbeat
2017-12-05T11:14:12.790+0000 I REPL     [replExecDBWorker-0] transition to SECONDARY
2017-12-05T11:14:12.790+0000 I NETWORK  [replExecDBWorker-0] legacy transport layer closing all connections
2017-12-05T11:14:12.791+0000 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 8
2017-12-05T11:14:12.791+0000 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 5
2017-12-05T11:14:12.792+0000 I -        [conn4] end connection 127.0.0.1:53112 (3 connections now open)
2017-12-05T11:14:12.795+0000 I REPL     [ReplicationExecutor] Member 0.0.0.0:27019 is now in state STARTUP
2017-12-05T11:14:12.803+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38042 #19 (3 connections now open)
2017-12-05T11:14:12.803+0000 I REPL     [ReplicationExecutor] Member 0.0.0.0:27020 is now in state STARTUP
2017-12-05T11:14:12.804+0000 I -        [conn19] end connection 172.17.0.3:38042 (3 connections now open)
2017-12-05T11:14:13.320+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38044 #20 (3 connections now open)
2017-12-05T11:14:13.321+0000 I -        [conn20] end connection 172.17.0.3:38044 (3 connections now open)
2017-12-05T11:14:14.805+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38046 #21 (3 connections now open)
2017-12-05T11:14:14.807+0000 I -        [conn21] end connection 172.17.0.3:38046 (3 connections now open)
2017-12-05T11:14:15.322+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38048 #22 (3 connections now open)
2017-12-05T11:14:15.323+0000 I -        [conn22] end connection 172.17.0.3:38048 (3 connections now open)
2017-12-05T11:14:16.808+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38050 #23 (3 connections now open)
2017-12-05T11:14:16.810+0000 I -        [conn23] end connection 172.17.0.3:38050 (3 connections now open)
2017-12-05T11:14:17.324+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38052 #24 (3 connections now open)
2017-12-05T11:14:17.325+0000 I -        [conn24] end connection 172.17.0.3:38052 (3 connections now open)
2017-12-05T11:14:18.809+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38054 #25 (3 connections now open)
2017-12-05T11:14:18.810+0000 I -        [conn25] end connection 172.17.0.3:38054 (3 connections now open)
2017-12-05T11:14:19.325+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38056 #26 (3 connections now open)
2017-12-05T11:14:19.326+0000 I -        [conn26] end connection 172.17.0.3:38056 (3 connections now open)
2017-12-05T11:14:20.811+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38058 #27 (3 connections now open)
2017-12-05T11:14:20.812+0000 I -        [conn27] end connection 172.17.0.3:38058 (3 connections now open)
2017-12-05T11:14:21.326+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38060 #28 (3 connections now open)
2017-12-05T11:14:21.327+0000 I -        [conn28] end connection 172.17.0.3:38060 (3 connections now open)
2017-12-05T11:14:22.812+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38062 #29 (3 connections now open)
2017-12-05T11:14:22.813+0000 I -        [conn29] end connection 172.17.0.3:38062 (3 connections now open)
2017-12-05T11:14:23.327+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38064 #30 (3 connections now open)
2017-12-05T11:14:23.328+0000 I -        [conn30] end connection 172.17.0.3:38064 (3 connections now open)
2017-12-05T11:14:23.847+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:14:23.848+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:14:23.849+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:23.849+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:23.850+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:14:24.814+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38066 #31 (3 connections now open)
2017-12-05T11:14:24.816+0000 I -        [conn31] end connection 172.17.0.3:38066 (3 connections now open)
2017-12-05T11:14:25.329+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38068 #32 (3 connections now open)
2017-12-05T11:14:25.330+0000 I -        [conn32] end connection 172.17.0.3:38068 (3 connections now open)
2017-12-05T11:14:26.814+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38070 #33 (3 connections now open)
2017-12-05T11:14:26.815+0000 I -        [conn33] end connection 172.17.0.3:38070 (3 connections now open)
2017-12-05T11:14:27.330+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38072 #34 (3 connections now open)
2017-12-05T11:14:27.331+0000 I -        [conn34] end connection 172.17.0.3:38072 (3 connections now open)
2017-12-05T11:14:28.815+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38074 #35 (3 connections now open)
2017-12-05T11:14:28.816+0000 I -        [conn35] end connection 172.17.0.3:38074 (3 connections now open)
2017-12-05T11:14:29.331+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38076 #36 (3 connections now open)
2017-12-05T11:14:29.332+0000 I -        [conn36] end connection 172.17.0.3:38076 (3 connections now open)
2017-12-05T11:14:30.815+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38078 #37 (3 connections now open)
2017-12-05T11:14:30.816+0000 I -        [conn37] end connection 172.17.0.3:38078 (3 connections now open)
2017-12-05T11:14:31.333+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38080 #38 (3 connections now open)
2017-12-05T11:14:31.335+0000 I -        [conn38] end connection 172.17.0.3:38080 (3 connections now open)
2017-12-05T11:14:32.817+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38082 #39 (3 connections now open)
2017-12-05T11:14:32.818+0000 I -        [conn39] end connection 172.17.0.3:38082 (3 connections now open)
2017-12-05T11:14:33.336+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38084 #40 (3 connections now open)
2017-12-05T11:14:33.337+0000 I -        [conn40] end connection 172.17.0.3:38084 (3 connections now open)
2017-12-05T11:14:33.946+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:14:33.956+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:14:33.957+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:33.958+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:33.958+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:14:34.819+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38086 #41 (3 connections now open)
2017-12-05T11:14:34.820+0000 I -        [conn41] end connection 172.17.0.3:38086 (3 connections now open)
2017-12-05T11:14:35.337+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38088 #42 (3 connections now open)
2017-12-05T11:14:35.338+0000 I -        [conn42] end connection 172.17.0.3:38088 (3 connections now open)
2017-12-05T11:14:36.820+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38090 #43 (3 connections now open)
2017-12-05T11:14:36.821+0000 I -        [conn43] end connection 172.17.0.3:38090 (3 connections now open)
2017-12-05T11:14:37.338+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38092 #44 (3 connections now open)
2017-12-05T11:14:37.339+0000 I -        [conn44] end connection 172.17.0.3:38092 (3 connections now open)
2017-12-05T11:14:38.821+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38094 #45 (3 connections now open)
2017-12-05T11:14:38.823+0000 I -        [conn45] end connection 172.17.0.3:38094 (3 connections now open)
2017-12-05T11:14:39.340+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38096 #46 (3 connections now open)
2017-12-05T11:14:39.341+0000 I -        [conn46] end connection 172.17.0.3:38096 (3 connections now open)
2017-12-05T11:14:40.823+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38098 #47 (3 connections now open)
2017-12-05T11:14:40.824+0000 I -        [conn47] end connection 172.17.0.3:38098 (3 connections now open)
2017-12-05T11:14:41.342+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38100 #48 (3 connections now open)
2017-12-05T11:14:41.343+0000 I -        [conn48] end connection 172.17.0.3:38100 (3 connections now open)
2017-12-05T11:14:42.824+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38102 #49 (3 connections now open)
2017-12-05T11:14:42.825+0000 I -        [conn49] end connection 172.17.0.3:38102 (3 connections now open)
2017-12-05T11:14:43.343+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38104 #50 (3 connections now open)
2017-12-05T11:14:43.344+0000 I -        [conn50] end connection 172.17.0.3:38104 (3 connections now open)
2017-12-05T11:14:44.825+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38106 #51 (3 connections now open)
2017-12-05T11:14:44.826+0000 I -        [conn51] end connection 172.17.0.3:38106 (3 connections now open)
2017-12-05T11:14:45.049+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:14:45.049+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:14:45.050+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:45.051+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:45.051+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:14:45.343+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38108 #52 (3 connections now open)
2017-12-05T11:14:45.344+0000 I -        [conn52] end connection 172.17.0.3:38108 (3 connections now open)
2017-12-05T11:14:46.826+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38110 #53 (3 connections now open)
2017-12-05T11:14:46.826+0000 I -        [conn53] end connection 172.17.0.3:38110 (3 connections now open)
2017-12-05T11:14:47.345+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38112 #54 (3 connections now open)
2017-12-05T11:14:47.346+0000 I -        [conn54] end connection 172.17.0.3:38112 (3 connections now open)
2017-12-05T11:14:48.826+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38114 #55 (3 connections now open)
2017-12-05T11:14:48.833+0000 I -        [conn55] end connection 172.17.0.3:38114 (3 connections now open)
2017-12-05T11:14:49.346+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38116 #56 (3 connections now open)
2017-12-05T11:14:49.348+0000 I -        [conn56] end connection 172.17.0.3:38116 (3 connections now open)
2017-12-05T11:14:50.828+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38118 #57 (3 connections now open)
2017-12-05T11:14:50.829+0000 I -        [conn57] end connection 172.17.0.3:38118 (3 connections now open)
2017-12-05T11:14:51.348+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38120 #58 (3 connections now open)
2017-12-05T11:14:51.349+0000 I -        [conn58] end connection 172.17.0.3:38120 (3 connections now open)
2017-12-05T11:14:52.828+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38122 #59 (3 connections now open)
2017-12-05T11:14:52.829+0000 I -        [conn59] end connection 172.17.0.3:38122 (3 connections now open)
2017-12-05T11:14:53.349+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38124 #60 (3 connections now open)
2017-12-05T11:14:53.350+0000 I -        [conn60] end connection 172.17.0.3:38124 (3 connections now open)
2017-12-05T11:14:54.829+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38126 #61 (3 connections now open)
2017-12-05T11:14:54.830+0000 I -        [conn61] end connection 172.17.0.3:38126 (3 connections now open)
2017-12-05T11:14:55.351+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38128 #62 (3 connections now open)
2017-12-05T11:14:55.352+0000 I -        [conn62] end connection 172.17.0.3:38128 (3 connections now open)
2017-12-05T11:14:56.415+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:14:56.416+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:14:56.417+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:56.417+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:14:56.418+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:14:56.830+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38130 #63 (3 connections now open)
2017-12-05T11:14:56.830+0000 I -        [conn63] end connection 172.17.0.3:38130 (3 connections now open)
2017-12-05T11:14:57.352+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38132 #64 (3 connections now open)
2017-12-05T11:14:57.353+0000 I -        [conn64] end connection 172.17.0.3:38132 (3 connections now open)
2017-12-05T11:14:58.831+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38134 #65 (3 connections now open)
2017-12-05T11:14:58.832+0000 I -        [conn65] end connection 172.17.0.3:38134 (3 connections now open)
2017-12-05T11:14:59.354+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38136 #66 (3 connections now open)
2017-12-05T11:14:59.355+0000 I -        [conn66] end connection 172.17.0.3:38136 (3 connections now open)
2017-12-05T11:15:00.831+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38138 #67 (3 connections now open)
2017-12-05T11:15:00.832+0000 I -        [conn67] end connection 172.17.0.3:38138 (3 connections now open)
2017-12-05T11:15:01.357+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38140 #68 (3 connections now open)
2017-12-05T11:15:01.359+0000 I -        [conn68] end connection 172.17.0.3:38140 (3 connections now open)
2017-12-05T11:15:02.794+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host 0.0.0.0:27020 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T11:15:02.833+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38142 #69 (3 connections now open)
2017-12-05T11:15:02.834+0000 I -        [conn69] end connection 172.17.0.3:38142 (3 connections now open)
2017-12-05T11:15:03.359+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38144 #70 (3 connections now open)
2017-12-05T11:15:03.360+0000 I -        [conn70] end connection 172.17.0.3:38144 (3 connections now open)
2017-12-05T11:15:04.835+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38146 #71 (3 connections now open)
2017-12-05T11:15:04.841+0000 I -        [conn71] end connection 172.17.0.3:38146 (3 connections now open)
2017-12-05T11:15:05.360+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38148 #72 (3 connections now open)
2017-12-05T11:15:05.361+0000 I -        [conn72] end connection 172.17.0.3:38148 (3 connections now open)
2017-12-05T11:15:06.530+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:15:06.530+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:15:06.531+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:06.531+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:06.532+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:15:06.836+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38150 #73 (3 connections now open)
2017-12-05T11:15:06.837+0000 I -        [conn73] end connection 172.17.0.3:38150 (3 connections now open)
2017-12-05T11:15:07.362+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38152 #74 (3 connections now open)
2017-12-05T11:15:07.363+0000 I -        [conn74] end connection 172.17.0.3:38152 (3 connections now open)
2017-12-05T11:15:08.836+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38154 #75 (3 connections now open)
2017-12-05T11:15:08.837+0000 I -        [conn75] end connection 172.17.0.3:38154 (3 connections now open)
2017-12-05T11:15:09.363+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38156 #76 (3 connections now open)
2017-12-05T11:15:09.365+0000 I -        [conn76] end connection 172.17.0.3:38156 (3 connections now open)
2017-12-05T11:15:10.840+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38158 #77 (3 connections now open)
2017-12-05T11:15:10.841+0000 I -        [conn77] end connection 172.17.0.3:38158 (3 connections now open)
2017-12-05T11:15:11.365+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38160 #78 (3 connections now open)
2017-12-05T11:15:11.366+0000 I -        [conn78] end connection 172.17.0.3:38160 (3 connections now open)
2017-12-05T11:15:12.841+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38162 #79 (3 connections now open)
2017-12-05T11:15:12.842+0000 I -        [conn79] end connection 172.17.0.3:38162 (3 connections now open)
2017-12-05T11:15:13.366+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38164 #80 (3 connections now open)
2017-12-05T11:15:13.367+0000 I -        [conn80] end connection 172.17.0.3:38164 (3 connections now open)
2017-12-05T11:15:14.843+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38166 #81 (3 connections now open)
2017-12-05T11:15:14.845+0000 I -        [conn81] end connection 172.17.0.3:38166 (3 connections now open)
2017-12-05T11:15:15.367+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38168 #82 (3 connections now open)
2017-12-05T11:15:15.368+0000 I -        [conn82] end connection 172.17.0.3:38168 (3 connections now open)
2017-12-05T11:15:16.845+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38170 #83 (3 connections now open)
2017-12-05T11:15:16.846+0000 I -        [conn83] end connection 172.17.0.3:38170 (3 connections now open)
2017-12-05T11:15:17.369+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38172 #84 (3 connections now open)
2017-12-05T11:15:17.370+0000 I -        [conn84] end connection 172.17.0.3:38172 (3 connections now open)
2017-12-05T11:15:17.954+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:15:17.955+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:15:17.956+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:17.956+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:17.957+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:15:18.848+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38174 #85 (3 connections now open)
2017-12-05T11:15:18.849+0000 I -        [conn85] end connection 172.17.0.3:38174 (3 connections now open)
2017-12-05T11:15:19.370+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38176 #86 (3 connections now open)
2017-12-05T11:15:19.371+0000 I -        [conn86] end connection 172.17.0.3:38176 (3 connections now open)
2017-12-05T11:15:20.849+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38178 #87 (3 connections now open)
2017-12-05T11:15:20.850+0000 I -        [conn87] end connection 172.17.0.3:38178 (3 connections now open)
2017-12-05T11:15:21.372+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38180 #88 (3 connections now open)
2017-12-05T11:15:21.373+0000 I -        [conn88] end connection 172.17.0.3:38180 (3 connections now open)
2017-12-05T11:15:22.849+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38182 #89 (3 connections now open)
2017-12-05T11:15:22.851+0000 I -        [conn89] end connection 172.17.0.3:38182 (3 connections now open)
2017-12-05T11:15:23.374+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38184 #90 (3 connections now open)
2017-12-05T11:15:23.375+0000 I -        [conn90] end connection 172.17.0.3:38184 (3 connections now open)
2017-12-05T11:15:24.851+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38186 #91 (3 connections now open)
2017-12-05T11:15:24.852+0000 I -        [conn91] end connection 172.17.0.3:38186 (3 connections now open)
2017-12-05T11:15:25.375+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38188 #92 (3 connections now open)
2017-12-05T11:15:25.376+0000 I -        [conn92] end connection 172.17.0.3:38188 (3 connections now open)
2017-12-05T11:15:26.852+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38190 #93 (3 connections now open)
2017-12-05T11:15:26.853+0000 I -        [conn93] end connection 172.17.0.3:38190 (3 connections now open)
2017-12-05T11:15:27.377+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38192 #94 (3 connections now open)
2017-12-05T11:15:27.379+0000 I -        [conn94] end connection 172.17.0.3:38192 (3 connections now open)
2017-12-05T11:15:28.312+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:15:28.312+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:15:28.313+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:28.313+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:28.314+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:15:28.853+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38194 #95 (3 connections now open)
2017-12-05T11:15:28.854+0000 I -        [conn95] end connection 172.17.0.3:38194 (3 connections now open)
2017-12-05T11:15:29.377+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38196 #96 (3 connections now open)
2017-12-05T11:15:29.378+0000 I -        [conn96] end connection 172.17.0.3:38196 (3 connections now open)
2017-12-05T11:15:30.855+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38198 #97 (3 connections now open)
2017-12-05T11:15:30.855+0000 I -        [conn97] end connection 172.17.0.3:38198 (3 connections now open)
2017-12-05T11:15:31.379+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38200 #98 (3 connections now open)
2017-12-05T11:15:31.380+0000 I -        [conn98] end connection 172.17.0.3:38200 (3 connections now open)
2017-12-05T11:15:32.855+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38202 #99 (3 connections now open)
2017-12-05T11:15:32.857+0000 I -        [conn99] end connection 172.17.0.3:38202 (3 connections now open)
2017-12-05T11:15:33.380+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38204 #100 (3 connections now open)
2017-12-05T11:15:33.380+0000 I -        [conn100] end connection 172.17.0.3:38204 (3 connections now open)
2017-12-05T11:15:34.857+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38206 #101 (3 connections now open)
2017-12-05T11:15:34.858+0000 I -        [conn101] end connection 172.17.0.3:38206 (3 connections now open)
2017-12-05T11:15:35.381+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38208 #102 (3 connections now open)
2017-12-05T11:15:35.382+0000 I -        [conn102] end connection 172.17.0.3:38208 (3 connections now open)
2017-12-05T11:15:36.859+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38210 #103 (3 connections now open)
2017-12-05T11:15:36.860+0000 I -        [conn103] end connection 172.17.0.3:38210 (3 connections now open)
2017-12-05T11:15:37.382+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38212 #104 (3 connections now open)
2017-12-05T11:15:37.389+0000 I -        [conn104] end connection 172.17.0.3:38212 (3 connections now open)
2017-12-05T11:15:38.860+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38214 #105 (3 connections now open)
2017-12-05T11:15:38.861+0000 I -        [conn105] end connection 172.17.0.3:38214 (3 connections now open)
2017-12-05T11:15:39.384+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38216 #106 (3 connections now open)
2017-12-05T11:15:39.385+0000 I -        [conn106] end connection 172.17.0.3:38216 (3 connections now open)
2017-12-05T11:15:39.428+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:15:39.429+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:15:39.430+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:39.431+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:39.431+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:15:40.861+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38218 #107 (3 connections now open)
2017-12-05T11:15:40.862+0000 I -        [conn107] end connection 172.17.0.3:38218 (3 connections now open)
2017-12-05T11:15:41.385+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38220 #108 (3 connections now open)
2017-12-05T11:15:41.386+0000 I -        [conn108] end connection 172.17.0.3:38220 (3 connections now open)
2017-12-05T11:15:42.862+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38222 #109 (3 connections now open)
2017-12-05T11:15:42.863+0000 I -        [conn109] end connection 172.17.0.3:38222 (3 connections now open)
2017-12-05T11:15:43.386+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38224 #110 (3 connections now open)
2017-12-05T11:15:43.387+0000 I -        [conn110] end connection 172.17.0.3:38224 (3 connections now open)
2017-12-05T11:15:44.864+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38226 #111 (3 connections now open)
2017-12-05T11:15:44.865+0000 I -        [conn111] end connection 172.17.0.3:38226 (3 connections now open)
2017-12-05T11:15:45.387+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38228 #112 (3 connections now open)
2017-12-05T11:15:45.388+0000 I -        [conn112] end connection 172.17.0.3:38228 (3 connections now open)
2017-12-05T11:15:46.866+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38230 #113 (3 connections now open)
2017-12-05T11:15:46.867+0000 I -        [conn113] end connection 172.17.0.3:38230 (3 connections now open)
2017-12-05T11:15:47.389+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38232 #114 (3 connections now open)
2017-12-05T11:15:47.390+0000 I -        [conn114] end connection 172.17.0.3:38232 (3 connections now open)
2017-12-05T11:15:48.867+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38234 #115 (3 connections now open)
2017-12-05T11:15:48.868+0000 I -        [conn115] end connection 172.17.0.3:38234 (3 connections now open)
2017-12-05T11:15:49.389+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38236 #116 (3 connections now open)
2017-12-05T11:15:49.390+0000 I -        [conn116] end connection 172.17.0.3:38236 (3 connections now open)
2017-12-05T11:15:50.518+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:15:50.519+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:15:50.520+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:50.520+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:15:50.521+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:15:50.868+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38238 #117 (3 connections now open)
2017-12-05T11:15:50.869+0000 I -        [conn117] end connection 172.17.0.3:38238 (3 connections now open)
2017-12-05T11:15:51.390+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38240 #118 (3 connections now open)
2017-12-05T11:15:51.391+0000 I -        [conn118] end connection 172.17.0.3:38240 (3 connections now open)
2017-12-05T11:15:52.870+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38242 #119 (3 connections now open)
2017-12-05T11:15:52.871+0000 I -        [conn119] end connection 172.17.0.3:38242 (3 connections now open)
2017-12-05T11:15:53.391+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38244 #120 (3 connections now open)
2017-12-05T11:15:53.392+0000 I -        [conn120] end connection 172.17.0.3:38244 (3 connections now open)
2017-12-05T11:15:54.871+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38246 #121 (3 connections now open)
2017-12-05T11:15:54.872+0000 I -        [conn121] end connection 172.17.0.3:38246 (3 connections now open)
2017-12-05T11:15:55.393+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38248 #122 (3 connections now open)
2017-12-05T11:15:55.394+0000 I -        [conn122] end connection 172.17.0.3:38248 (3 connections now open)
2017-12-05T11:15:56.873+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38250 #123 (3 connections now open)
2017-12-05T11:15:56.874+0000 I -        [conn123] end connection 172.17.0.3:38250 (3 connections now open)
2017-12-05T11:15:57.394+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38252 #124 (3 connections now open)
2017-12-05T11:15:57.395+0000 I -        [conn124] end connection 172.17.0.3:38252 (3 connections now open)
2017-12-05T11:15:58.874+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38254 #125 (3 connections now open)
2017-12-05T11:15:58.875+0000 I -        [conn125] end connection 172.17.0.3:38254 (3 connections now open)
2017-12-05T11:15:59.395+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38256 #126 (3 connections now open)
2017-12-05T11:15:59.395+0000 I -        [conn126] end connection 172.17.0.3:38256 (3 connections now open)
2017-12-05T11:16:00.875+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38258 #127 (3 connections now open)
2017-12-05T11:16:00.876+0000 I -        [conn127] end connection 172.17.0.3:38258 (3 connections now open)
2017-12-05T11:16:01.395+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38260 #128 (3 connections now open)
2017-12-05T11:16:01.396+0000 I -        [conn128] end connection 172.17.0.3:38260 (3 connections now open)
2017-12-05T11:16:01.518+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:16:01.523+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:16:01.527+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:01.527+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:01.528+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:16:02.876+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38262 #129 (3 connections now open)
2017-12-05T11:16:02.877+0000 I -        [conn129] end connection 172.17.0.3:38262 (3 connections now open)
2017-12-05T11:16:03.397+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38264 #130 (3 connections now open)
2017-12-05T11:16:03.398+0000 I -        [conn130] end connection 172.17.0.3:38264 (3 connections now open)
2017-12-05T11:16:04.878+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38266 #131 (3 connections now open)
2017-12-05T11:16:04.879+0000 I -        [conn131] end connection 172.17.0.3:38266 (3 connections now open)
2017-12-05T11:16:05.398+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38268 #132 (3 connections now open)
2017-12-05T11:16:05.399+0000 I -        [conn132] end connection 172.17.0.3:38268 (3 connections now open)
2017-12-05T11:16:06.879+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38270 #133 (3 connections now open)
2017-12-05T11:16:06.880+0000 I -        [conn133] end connection 172.17.0.3:38270 (3 connections now open)
2017-12-05T11:16:07.399+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38272 #134 (3 connections now open)
2017-12-05T11:16:07.401+0000 I -        [conn134] end connection 172.17.0.3:38272 (3 connections now open)
2017-12-05T11:16:08.883+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38274 #135 (3 connections now open)
2017-12-05T11:16:08.884+0000 I -        [conn135] end connection 172.17.0.3:38274 (3 connections now open)
2017-12-05T11:16:09.400+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38276 #136 (3 connections now open)
2017-12-05T11:16:09.401+0000 I -        [conn136] end connection 172.17.0.3:38276 (3 connections now open)
2017-12-05T11:16:10.885+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38278 #137 (3 connections now open)
2017-12-05T11:16:10.886+0000 I -        [conn137] end connection 172.17.0.3:38278 (3 connections now open)
2017-12-05T11:16:11.403+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38280 #138 (3 connections now open)
2017-12-05T11:16:11.404+0000 I -        [conn138] end connection 172.17.0.3:38280 (3 connections now open)
2017-12-05T11:16:12.886+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38282 #139 (3 connections now open)
2017-12-05T11:16:12.887+0000 I -        [conn139] end connection 172.17.0.3:38282 (3 connections now open)
2017-12-05T11:16:12.924+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:16:12.924+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:16:12.925+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:12.926+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:12.927+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:16:13.404+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38284 #140 (3 connections now open)
2017-12-05T11:16:13.405+0000 I -        [conn140] end connection 172.17.0.3:38284 (3 connections now open)
2017-12-05T11:16:14.887+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38286 #141 (3 connections now open)
2017-12-05T11:16:14.888+0000 I -        [conn141] end connection 172.17.0.3:38286 (3 connections now open)
2017-12-05T11:16:15.405+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38288 #142 (3 connections now open)
2017-12-05T11:16:15.406+0000 I -        [conn142] end connection 172.17.0.3:38288 (3 connections now open)
2017-12-05T11:16:16.891+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38290 #143 (3 connections now open)
2017-12-05T11:16:16.893+0000 I -        [conn143] end connection 172.17.0.3:38290 (3 connections now open)
2017-12-05T11:16:17.406+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38292 #144 (3 connections now open)
2017-12-05T11:16:17.407+0000 I -        [conn144] end connection 172.17.0.3:38292 (3 connections now open)
2017-12-05T11:16:18.892+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38294 #145 (3 connections now open)
2017-12-05T11:16:18.893+0000 I -        [conn145] end connection 172.17.0.3:38294 (3 connections now open)
2017-12-05T11:16:19.407+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38296 #146 (3 connections now open)
2017-12-05T11:16:19.408+0000 I -        [conn146] end connection 172.17.0.3:38296 (3 connections now open)
2017-12-05T11:16:20.894+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38298 #147 (3 connections now open)
2017-12-05T11:16:20.895+0000 I -        [conn147] end connection 172.17.0.3:38298 (3 connections now open)
2017-12-05T11:16:21.408+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38300 #148 (3 connections now open)
2017-12-05T11:16:21.409+0000 I -        [conn148] end connection 172.17.0.3:38300 (3 connections now open)
2017-12-05T11:16:22.895+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38302 #149 (3 connections now open)
2017-12-05T11:16:22.896+0000 I -        [conn149] end connection 172.17.0.3:38302 (3 connections now open)
2017-12-05T11:16:23.409+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38304 #150 (3 connections now open)
2017-12-05T11:16:23.416+0000 I -        [conn150] end connection 172.17.0.3:38304 (3 connections now open)
2017-12-05T11:16:23.829+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:16:23.830+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:16:23.831+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:23.832+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:23.832+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:16:24.896+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38306 #151 (3 connections now open)
2017-12-05T11:16:24.897+0000 I -        [conn151] end connection 172.17.0.3:38306 (3 connections now open)
2017-12-05T11:16:25.411+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38308 #152 (3 connections now open)
2017-12-05T11:16:25.412+0000 I -        [conn152] end connection 172.17.0.3:38308 (3 connections now open)
2017-12-05T11:16:26.899+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38310 #153 (3 connections now open)
2017-12-05T11:16:26.902+0000 I -        [conn153] end connection 172.17.0.3:38310 (3 connections now open)
2017-12-05T11:16:27.412+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38312 #154 (3 connections now open)
2017-12-05T11:16:27.413+0000 I -        [conn154] end connection 172.17.0.3:38312 (3 connections now open)
2017-12-05T11:16:28.901+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38314 #155 (3 connections now open)
2017-12-05T11:16:28.902+0000 I -        [conn155] end connection 172.17.0.3:38314 (3 connections now open)
2017-12-05T11:16:29.413+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38316 #156 (3 connections now open)
2017-12-05T11:16:29.414+0000 I -        [conn156] end connection 172.17.0.3:38316 (3 connections now open)
2017-12-05T11:16:30.902+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38318 #157 (3 connections now open)
2017-12-05T11:16:30.903+0000 I -        [conn157] end connection 172.17.0.3:38318 (3 connections now open)
2017-12-05T11:16:31.415+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38320 #158 (3 connections now open)
2017-12-05T11:16:31.416+0000 I -        [conn158] end connection 172.17.0.3:38320 (3 connections now open)
2017-12-05T11:16:32.903+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38322 #159 (3 connections now open)
2017-12-05T11:16:32.904+0000 I -        [conn159] end connection 172.17.0.3:38322 (3 connections now open)
2017-12-05T11:16:33.417+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38324 #160 (3 connections now open)
2017-12-05T11:16:33.421+0000 I -        [conn160] end connection 172.17.0.3:38324 (3 connections now open)
2017-12-05T11:16:34.904+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38326 #161 (3 connections now open)
2017-12-05T11:16:34.915+0000 I -        [conn161] end connection 172.17.0.3:38326 (3 connections now open)
2017-12-05T11:16:35.088+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:16:35.088+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:16:35.089+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:35.090+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:35.090+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:16:35.418+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38328 #162 (3 connections now open)
2017-12-05T11:16:35.419+0000 I -        [conn162] end connection 172.17.0.3:38328 (3 connections now open)
2017-12-05T11:16:36.906+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38330 #163 (3 connections now open)
2017-12-05T11:16:36.907+0000 I -        [conn163] end connection 172.17.0.3:38330 (3 connections now open)
2017-12-05T11:16:37.419+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38332 #164 (3 connections now open)
2017-12-05T11:16:37.420+0000 I -        [conn164] end connection 172.17.0.3:38332 (3 connections now open)
2017-12-05T11:16:38.907+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38334 #165 (3 connections now open)
2017-12-05T11:16:38.908+0000 I -        [conn165] end connection 172.17.0.3:38334 (3 connections now open)
2017-12-05T11:16:39.419+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38336 #166 (3 connections now open)
2017-12-05T11:16:39.420+0000 I -        [conn166] end connection 172.17.0.3:38336 (3 connections now open)
2017-12-05T11:16:40.908+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38338 #167 (3 connections now open)
2017-12-05T11:16:40.909+0000 I -        [conn167] end connection 172.17.0.3:38338 (3 connections now open)
2017-12-05T11:16:41.421+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38340 #168 (3 connections now open)
2017-12-05T11:16:41.422+0000 I -        [conn168] end connection 172.17.0.3:38340 (3 connections now open)
2017-12-05T11:16:42.909+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38342 #169 (3 connections now open)
2017-12-05T11:16:42.910+0000 I -        [conn169] end connection 172.17.0.3:38342 (3 connections now open)
2017-12-05T11:16:43.421+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38344 #170 (3 connections now open)
2017-12-05T11:16:43.422+0000 I -        [conn170] end connection 172.17.0.3:38344 (3 connections now open)
2017-12-05T11:16:44.910+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38346 #171 (3 connections now open)
2017-12-05T11:16:44.911+0000 I -        [conn171] end connection 172.17.0.3:38346 (3 connections now open)
2017-12-05T11:16:45.423+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38348 #172 (3 connections now open)
2017-12-05T11:16:45.424+0000 I -        [conn172] end connection 172.17.0.3:38348 (3 connections now open)
2017-12-05T11:16:45.651+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:16:45.652+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:16:45.653+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:45.654+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:45.654+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:16:46.912+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38350 #173 (3 connections now open)
2017-12-05T11:16:46.913+0000 I -        [conn173] end connection 172.17.0.3:38350 (3 connections now open)
2017-12-05T11:16:47.426+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38352 #174 (3 connections now open)
2017-12-05T11:16:47.427+0000 I -        [conn174] end connection 172.17.0.3:38352 (3 connections now open)
2017-12-05T11:16:48.915+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38354 #175 (3 connections now open)
2017-12-05T11:16:48.916+0000 I -        [conn175] end connection 172.17.0.3:38354 (3 connections now open)
2017-12-05T11:16:49.428+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38356 #176 (3 connections now open)
2017-12-05T11:16:49.429+0000 I -        [conn176] end connection 172.17.0.3:38356 (3 connections now open)
2017-12-05T11:16:50.917+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38358 #177 (3 connections now open)
2017-12-05T11:16:50.918+0000 I -        [conn177] end connection 172.17.0.3:38358 (3 connections now open)
2017-12-05T11:16:51.429+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38360 #178 (3 connections now open)
2017-12-05T11:16:51.429+0000 I -        [conn178] end connection 172.17.0.3:38360 (3 connections now open)
2017-12-05T11:16:52.918+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38362 #179 (3 connections now open)
2017-12-05T11:16:52.919+0000 I -        [conn179] end connection 172.17.0.3:38362 (3 connections now open)
2017-12-05T11:16:53.430+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38364 #180 (3 connections now open)
2017-12-05T11:16:53.431+0000 I -        [conn180] end connection 172.17.0.3:38364 (3 connections now open)
2017-12-05T11:16:54.919+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38366 #181 (3 connections now open)
2017-12-05T11:16:54.920+0000 I -        [conn181] end connection 172.17.0.3:38366 (3 connections now open)
2017-12-05T11:16:55.432+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38368 #182 (3 connections now open)
2017-12-05T11:16:55.433+0000 I -        [conn182] end connection 172.17.0.3:38368 (3 connections now open)
2017-12-05T11:16:55.890+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:16:55.891+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:16:55.892+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:55.893+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:16:55.893+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:16:56.920+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38370 #183 (3 connections now open)
2017-12-05T11:16:56.921+0000 I -        [conn183] end connection 172.17.0.3:38370 (3 connections now open)
2017-12-05T11:16:57.433+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38372 #184 (3 connections now open)
2017-12-05T11:16:57.435+0000 I -        [conn184] end connection 172.17.0.3:38372 (3 connections now open)
2017-12-05T11:16:58.921+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38374 #185 (3 connections now open)
2017-12-05T11:16:58.922+0000 I -        [conn185] end connection 172.17.0.3:38374 (3 connections now open)
2017-12-05T11:16:59.434+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38376 #186 (3 connections now open)
2017-12-05T11:16:59.435+0000 I -        [conn186] end connection 172.17.0.3:38376 (3 connections now open)
2017-12-05T11:17:00.922+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38378 #187 (3 connections now open)
2017-12-05T11:17:00.923+0000 I -        [conn187] end connection 172.17.0.3:38378 (3 connections now open)
2017-12-05T11:17:01.437+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38380 #188 (3 connections now open)
2017-12-05T11:17:01.438+0000 I -        [conn188] end connection 172.17.0.3:38380 (3 connections now open)
2017-12-05T11:17:02.924+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38382 #189 (3 connections now open)
2017-12-05T11:17:02.925+0000 I -        [conn189] end connection 172.17.0.3:38382 (3 connections now open)
2017-12-05T11:17:03.438+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38384 #190 (3 connections now open)
2017-12-05T11:17:03.439+0000 I -        [conn190] end connection 172.17.0.3:38384 (3 connections now open)
2017-12-05T11:17:04.925+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38386 #191 (3 connections now open)
2017-12-05T11:17:04.935+0000 I -        [conn191] end connection 172.17.0.3:38386 (3 connections now open)
2017-12-05T11:17:05.439+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38388 #192 (3 connections now open)
2017-12-05T11:17:05.440+0000 I -        [conn192] end connection 172.17.0.3:38388 (3 connections now open)
2017-12-05T11:17:06.926+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38390 #193 (3 connections now open)
2017-12-05T11:17:06.927+0000 I -        [conn193] end connection 172.17.0.3:38390 (3 connections now open)
2017-12-05T11:17:07.063+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:17:07.064+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:17:07.065+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27019: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27019 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:17:07.066+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received an invalid response from 0.0.0.0:27020: BadValue: Unexpected field info in ReplSetRequestVotesreceived a no vote from 0.0.0.0:27020 with reason ""; response message: { info: "run rs.initiate(...) if not yet done for the set", ok: 0.0, errmsg: "no replset config has been received", code: 94, codeName: "NotYetInitialized" }
2017-12-05T11:17:07.066+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-12-05T11:17:07.439+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38392 #194 (3 connections now open)
2017-12-05T11:17:07.440+0000 I -        [conn194] end connection 172.17.0.3:38392 (3 connections now open)
2017-12-05T11:17:08.927+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38394 #195 (3 connections now open)
2017-12-05T11:17:08.928+0000 I -        [conn195] end connection 172.17.0.3:38394 (3 connections now open)
2017-12-05T11:17:09.440+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38396 #196 (3 connections now open)
2017-12-05T11:17:09.441+0000 I -        [conn196] end connection 172.17.0.3:38396 (3 connections now open)
2017-12-05T11:17:10.929+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38398 #197 (3 connections now open)
2017-12-05T11:17:10.930+0000 I -        [conn197] end connection 172.17.0.3:38398 (3 connections now open)
2017-12-05T11:17:11.442+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38400 #198 (3 connections now open)
2017-12-05T11:17:11.443+0000 I -        [conn198] end connection 172.17.0.3:38400 (3 connections now open)
2017-12-05T11:17:12.932+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38402 #199 (3 connections now open)
2017-12-05T11:17:12.933+0000 I -        [conn199] end connection 172.17.0.3:38402 (3 connections now open)
2017-12-05T11:17:13.444+0000 I NETWORK  [thread1] connection accepted from 172.17.0.3:38404 #200 (3 connections now open)
2017-12-05T11:17:13.444+0000 I -        [conn200] end connection 172.17.0.3:38404 (3 connections now open)
2017-12-05T11:17:14.251+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
2017-12-05T11:17:14.251+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2017-12-05T11:17:14.251+0000 I NETWORK  [signalProcessingThread] closing listening socket: 7
2017-12-05T11:17:14.252+0000 I NETWORK  [signalProcessingThread] closing listening socket: 8
2017-12-05T11:17:14.252+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27018.sock
2017-12-05T11:17:14.252+0000 I NETWORK  [signalProcessingThread] shutdown: going to flush diaglog...
2017-12-05T11:17:14.252+0000 I REPL     [signalProcessingThread] shutting down replication subsystems
2017-12-05T11:17:14.253+0000 I REPL     [signalProcessingThread] Stopping replication reporter thread
2017-12-05T11:17:14.253+0000 I REPL     [signalProcessingThread] Stopping replication fetcher thread
2017-12-05T11:17:14.253+0000 I REPL     [signalProcessingThread] Stopping replication applier thread
2017-12-05T11:17:14.376+0000 I REPL     [signalProcessingThread] Stopping replication storage threads
2017-12-05T11:17:14.377+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2017-12-05T11:17:14.389+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2017-12-05T11:17:14.515+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2017-12-05T11:17:14.515+0000 I CONTROL  [signalProcessingThread] now exiting
2017-12-05T11:17:14.515+0000 I CONTROL  [signalProcessingThread] shutting down with code:0
2017-12-05T11:17:14.515+0000 I CONTROL  [initandlisten] shutting down with code:0
2017-12-05T11:18:15.818+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2017-12-05T11:18:15.851+0000 I CONTROL  [initandlisten] MongoDB starting : pid=39 port=27018 dbpath=/data/27018/data 64-bit host=5d038de72a04
2017-12-05T11:18:15.851+0000 I CONTROL  [initandlisten] db version v3.4.10
2017-12-05T11:18:15.851+0000 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-05T11:18:15.851+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-12-05T11:18:15.852+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-05T11:18:15.852+0000 I CONTROL  [initandlisten] modules: none
2017-12-05T11:18:15.852+0000 I CONTROL  [initandlisten] build environment:
2017-12-05T11:18:15.852+0000 I CONTROL  [initandlisten]     distmod: rhel70
2017-12-05T11:18:15.853+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-05T11:18:15.853+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-05T11:18:15.853+0000 I CONTROL  [initandlisten] options: { config: "/conf/27018.conf", net: { http: { enabled: false }, maxIncomingConnections: 300, port: 27018 }, processManagement: { fork: true, pidFilePath: "/data/27018/logs/mongod.pid" }, replication: { replSet: "rs" }, storage: { dbPath: "/data/27018/data" }, systemLog: { destination: "file", logAppend: true, path: "/data/27018/logs/mongod.log" } }
2017-12-05T11:18:15.856+0000 I -        [initandlisten] Detected data files in /data/27018/data created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-12-05T11:18:15.859+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-05T11:18:23.637+0000 I STORAGE  [initandlisten] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-05T11:18:23.637+0000 I STORAGE  [initandlisten] The size storer reports that the oplog contains 6 records totaling to 588 bytes
2017-12-05T11:18:23.638+0000 I STORAGE  [initandlisten] Scanning the oplog to determine where to place markers for truncation
2017-12-05T11:18:23.666+0000 I CONTROL  [initandlisten] 
2017-12-05T11:18:23.667+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-05T11:18:23.667+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-05T11:18:23.667+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-05T11:18:23.667+0000 I CONTROL  [initandlisten] 
2017-12-05T11:18:23.677+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/27018/data/diagnostic.data'
2017-12-05T11:18:23.685+0000 I NETWORK  [thread1] waiting for connections on port 27018
2017-12-05T11:18:23.757+0000 W NETWORK  [replExecDBWorker-0] getaddrinfo("c526be9fe055") failed: Name or service not known
2017-12-05T11:18:23.759+0000 I NETWORK  [replExecDBWorker-0] getaddrinfo("c526be9fe055") failed: Name or service not known
2017-12-05T11:18:23.759+0000 W REPL     [replExecDBWorker-0] Locally stored replica set configuration does not have a valid entry for the current node; waiting for reconfig or remote heartbeat; Got "NodeNotFound: No host described in new configuration 3 for replica set rs maps to this node" while validating { _id: "rs", version: 3, protocolVersion: 1, members: [ { _id: 0, host: "c526be9fe055:27018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "0.0.0.0:27019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "0.0.0.0:27020", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a267f582897842bd42845cb') } }
2017-12-05T11:18:23.760+0000 I REPL     [replExecDBWorker-0] New replica set config in use: { _id: "rs", version: 3, protocolVersion: 1, members: [ { _id: 0, host: "c526be9fe055:27018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "0.0.0.0:27019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "0.0.0.0:27020", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a267f582897842bd42845cb') } }
2017-12-05T11:18:23.760+0000 I REPL     [replExecDBWorker-0] This node is not a member of the config
2017-12-05T11:18:23.760+0000 I REPL     [replExecDBWorker-0] transition to REMOVED
2017-12-05T11:18:23.761+0000 I NETWORK  [replExecDBWorker-0] legacy transport layer closing all connections
2017-12-05T11:18:23.761+0000 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-05T11:18:23.762+0000 I REPL     [replExecDBWorker-0] Starting replication fetcher thread
2017-12-05T11:18:23.763+0000 I REPL     [replExecDBWorker-0] Starting replication applier thread
2017-12-05T11:18:23.763+0000 I REPL     [replExecDBWorker-0] Starting replication reporter thread
2017-12-05T11:20:44.970+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54396 #1 (1 connection now open)
2017-12-05T11:20:44.976+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:54396 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:20:44.978+0000 I COMMAND  [conn1] initiate : no configuration specified. Using a default configuration for the set
2017-12-05T11:20:44.978+0000 I COMMAND  [conn1] created this configuration for initiation : { _id: "rs", version: 1, members: [ { _id: 0, host: "5d038de72a04:27018" } ] }
2017-12-05T11:20:44.978+0000 I REPL     [conn1] replSetInitiate admin command received from client
2017-12-05T11:20:44.980+0000 I REPL     [conn1] replSetReconfig admin command received from client
2017-12-05T11:20:44.981+0000 I REPL     [conn1] replSetReconfig admin command received from client
2017-12-05T11:20:44.983+0000 I -        [conn1] end connection 127.0.0.1:54396 (1 connection now open)
2017-12-05T11:20:53.014+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54398 #2 (1 connection now open)
2017-12-05T11:20:53.015+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:54398 conn2: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:21:09.179+0000 I -        [conn2] end connection 127.0.0.1:54398 (1 connection now open)
2017-12-05T11:21:11.716+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54400 #3 (1 connection now open)
2017-12-05T11:21:11.717+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:54400 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:21:11.719+0000 I COMMAND  [conn3] initiate : no configuration specified. Using a default configuration for the set
2017-12-05T11:21:11.719+0000 I COMMAND  [conn3] created this configuration for initiation : { _id: "rs", version: 1, members: [ { _id: 0, host: "5d038de72a04:27018" } ] }
2017-12-05T11:21:11.720+0000 I REPL     [conn3] replSetInitiate admin command received from client
2017-12-05T11:21:11.723+0000 I REPL     [conn3] replSetReconfig admin command received from client
2017-12-05T11:21:11.724+0000 I REPL     [conn3] replSetReconfig admin command received from client
2017-12-05T11:21:11.726+0000 I -        [conn3] end connection 127.0.0.1:54400 (1 connection now open)
2017-12-05T11:21:14.171+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54402 #4 (1 connection now open)
2017-12-05T11:21:14.172+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:54402 conn4: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:22:38.530+0000 I -        [conn4] end connection 127.0.0.1:54402 (1 connection now open)
2017-12-05T11:23:13.525+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54404 #5 (1 connection now open)
2017-12-05T11:23:13.526+0000 I NETWORK  [conn5] received client metadata from 127.0.0.1:54404 conn5: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:23:13.529+0000 I COMMAND  [conn5] initiate : no configuration specified. Using a default configuration for the set
2017-12-05T11:23:13.530+0000 I COMMAND  [conn5] created this configuration for initiation : { _id: "rs", version: 1, members: [ { _id: 0, host: "5d038de72a04:27018" } ] }
2017-12-05T11:23:13.530+0000 I REPL     [conn5] replSetInitiate admin command received from client
2017-12-05T11:23:13.534+0000 I REPL     [conn5] replSetReconfig admin command received from client
2017-12-05T11:23:13.535+0000 I REPL     [conn5] replSetReconfig admin command received from client
2017-12-05T11:23:13.537+0000 I -        [conn5] end connection 127.0.0.1:54404 (1 connection now open)
2017-12-05T11:23:16.992+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54406 #6 (1 connection now open)
2017-12-05T11:23:16.993+0000 I NETWORK  [conn6] received client metadata from 127.0.0.1:54406 conn6: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:23:36.786+0000 I -        [conn6] end connection 127.0.0.1:54406 (1 connection now open)
2017-12-05T11:24:15.430+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54408 #7 (1 connection now open)
2017-12-05T11:24:15.431+0000 I NETWORK  [conn7] received client metadata from 127.0.0.1:54408 conn7: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:24:15.433+0000 I COMMAND  [conn7] initiate : no configuration specified. Using a default configuration for the set
2017-12-05T11:24:15.433+0000 I COMMAND  [conn7] created this configuration for initiation : { _id: "rs", version: 1, members: [ { _id: 0, host: "5d038de72a04:27018" } ] }
2017-12-05T11:24:15.434+0000 I REPL     [conn7] replSetInitiate admin command received from client
2017-12-05T11:24:15.437+0000 I -        [conn7] end connection 127.0.0.1:54408 (1 connection now open)
2017-12-05T11:24:38.921+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54410 #8 (1 connection now open)
2017-12-05T11:24:38.922+0000 I NETWORK  [conn8] received client metadata from 127.0.0.1:54410 conn8: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:24:38.924+0000 I COMMAND  [conn8] initiate : no configuration specified. Using a default configuration for the set
2017-12-05T11:24:38.925+0000 I COMMAND  [conn8] created this configuration for initiation : { _id: "rs", version: 1, members: [ { _id: 0, host: "5d038de72a04:27018" } ] }
2017-12-05T11:24:38.925+0000 I REPL     [conn8] replSetInitiate admin command received from client
2017-12-05T11:24:38.928+0000 I REPL     [conn8] replSetReconfig admin command received from client
2017-12-05T11:24:38.929+0000 I REPL     [conn8] replSetReconfig admin command received from client
2017-12-05T11:24:38.931+0000 I -        [conn8] end connection 127.0.0.1:54410 (1 connection now open)
2017-12-05T11:24:44.640+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54412 #9 (1 connection now open)
2017-12-05T11:24:44.641+0000 I NETWORK  [conn9] received client metadata from 127.0.0.1:54412 conn9: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:25:38.438+0000 I -        [conn9] end connection 127.0.0.1:54412 (1 connection now open)
2017-12-05T11:26:00.979+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54414 #10 (1 connection now open)
2017-12-05T11:26:00.980+0000 I NETWORK  [conn10] received client metadata from 127.0.0.1:54414 conn10: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:26:00.981+0000 I COMMAND  [conn10] initiate : no configuration specified. Using a default configuration for the set
2017-12-05T11:26:00.982+0000 I COMMAND  [conn10] created this configuration for initiation : { _id: "rs", version: 1, members: [ { _id: 0, host: "5d038de72a04:27018" } ] }
2017-12-05T11:26:00.982+0000 I REPL     [conn10] replSetInitiate admin command received from client
2017-12-05T11:26:00.985+0000 I REPL     [conn10] replSetReconfig admin command received from client
2017-12-05T11:26:00.986+0000 I REPL     [conn10] replSetReconfig admin command received from client
2017-12-05T11:26:00.988+0000 I -        [conn10] end connection 127.0.0.1:54414 (1 connection now open)
2017-12-05T11:26:06.096+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54416 #11 (1 connection now open)
2017-12-05T11:26:06.097+0000 I NETWORK  [conn11] received client metadata from 127.0.0.1:54416 conn11: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:26:58.165+0000 I -        [conn11] end connection 127.0.0.1:54416 (1 connection now open)
2017-12-05T11:28:57.538+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54418 #12 (1 connection now open)
2017-12-05T11:28:57.544+0000 I NETWORK  [conn12] received client metadata from 127.0.0.1:54418 conn12: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:28:57.546+0000 I REPL     [conn12] replSetInitiate admin command received from client
2017-12-05T11:28:57.547+0000 I -        [conn12] end connection 127.0.0.1:54418 (1 connection now open)
2017-12-05T11:29:00.381+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54420 #13 (1 connection now open)
2017-12-05T11:29:00.382+0000 I NETWORK  [conn13] received client metadata from 127.0.0.1:54420 conn13: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:29:21.609+0000 I -        [conn13] end connection 127.0.0.1:54420 (1 connection now open)
2017-12-05T11:29:50.283+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54422 #14 (1 connection now open)
2017-12-05T11:29:50.284+0000 I NETWORK  [conn14] received client metadata from 127.0.0.1:54422 conn14: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:29:50.287+0000 I REPL     [conn14] replSetInitiate admin command received from client
2017-12-05T11:29:50.289+0000 I -        [conn14] end connection 127.0.0.1:54422 (1 connection now open)
2017-12-05T11:30:01.202+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54424 #15 (1 connection now open)
2017-12-05T11:30:01.203+0000 I NETWORK  [conn15] received client metadata from 127.0.0.1:54424 conn15: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:30:27.653+0000 I REPL     [conn15] replSetInitiate admin command received from client
2017-12-05T11:31:17.668+0000 I -        [conn15] end connection 127.0.0.1:54424 (1 connection now open)
2017-12-05T11:35:12.974+0000 E STORAGE  [thread2] WiredTiger error (2) [1512473712:974362][39:0x7fa6bc08f700], log-server: /data/27018/data/journal: directory-list: opendir: No such file or directory
2017-12-05T11:35:12.980+0000 E STORAGE  [thread2] WiredTiger error (2) [1512473712:980481][39:0x7fa6bc08f700], log-server: log pre-alloc server error: No such file or directory
2017-12-05T11:35:12.980+0000 E STORAGE  [thread2] WiredTiger error (2) [1512473712:980883][39:0x7fa6bc08f700], log-server: log server error: No such file or directory
2017-12-05T11:35:13.002+0000 E STORAGE  [ftdc] WiredTiger error (2) [1512473713:2935][39:0x7fa6b6884700], WT_SESSION.open_cursor: /data/27018/data/collection-4-7618540641943849882.wt: file-size: stat: No such file or directory
2017-12-05T11:35:13.012+0000 W FTDC     [ftdc] Uncaught exception in 'CursorNotFound: unable to open cursor at URI statistics:table:collection-4-7618540641943849882. reason: No such file or directory' in full-time diagnostic data capture subsystem. Shutting down the full-time diagnostic data capture subsystem.
2017-12-05T11:37:14.809+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2017-12-05T11:37:14.835+0000 I CONTROL  [initandlisten] MongoDB starting : pid=37 port=27018 dbpath=/data/27018/data 64-bit host=fa9fd8008b2d
2017-12-05T11:37:14.835+0000 I CONTROL  [initandlisten] db version v3.4.10
2017-12-05T11:37:14.835+0000 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-05T11:37:14.836+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-12-05T11:37:14.836+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-05T11:37:14.836+0000 I CONTROL  [initandlisten] modules: none
2017-12-05T11:37:14.836+0000 I CONTROL  [initandlisten] build environment:
2017-12-05T11:37:14.836+0000 I CONTROL  [initandlisten]     distmod: rhel70
2017-12-05T11:37:14.836+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-05T11:37:14.837+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-05T11:37:14.837+0000 I CONTROL  [initandlisten] options: { config: "/conf/27018.conf", net: { http: { enabled: false }, maxIncomingConnections: 300, port: 27018 }, processManagement: { fork: true, pidFilePath: "/data/27018/logs/mongod.pid" }, replication: { replSet: "rs" }, storage: { dbPath: "/data/27018/data" }, systemLog: { destination: "file", logAppend: true, path: "/data/27018/logs/mongod.log" } }
2017-12-05T11:37:14.840+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-05T11:37:19.962+0000 I CONTROL  [initandlisten] 
2017-12-05T11:37:19.962+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-05T11:37:19.963+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-05T11:37:19.963+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-05T11:37:19.963+0000 I CONTROL  [initandlisten] 
2017-12-05T11:37:19.973+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/27018/data/diagnostic.data'
2017-12-05T11:37:19.980+0000 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-05T11:37:19.980+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-05T11:37:19.981+0000 I NETWORK  [thread1] waiting for connections on port 27018
2017-12-05T11:39:11.317+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54426 #1 (1 connection now open)
2017-12-05T11:39:11.318+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:54426 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:11.321+0000 I REPL     [conn1] replSetInitiate admin command received from client
2017-12-05T11:39:11.323+0000 I REPL     [conn1] replSetInitiate config object with 3 members parses ok
2017-12-05T11:39:11.324+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27019
2017-12-05T11:39:11.325+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:39:11.326+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 127.0.0.1:27019, took 2ms (1 connections now open to 127.0.0.1:27019)
2017-12-05T11:39:11.326+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 127.0.0.1:27020, took 2ms (1 connections now open to 127.0.0.1:27020)
2017-12-05T11:39:11.327+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54436 #2 (2 connections now open)
2017-12-05T11:39:11.328+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54438 #3 (3 connections now open)
2017-12-05T11:39:11.328+0000 I REPL     [conn1] ******
2017-12-05T11:39:11.328+0000 I REPL     [conn1] creating replication oplog of size: 3147MB...
2017-12-05T11:39:11.328+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:54438 conn3: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:11.328+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:54436 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:11.332+0000 I STORAGE  [conn1] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-05T11:39:11.333+0000 I STORAGE  [conn1] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-05T11:39:11.333+0000 I STORAGE  [conn1] Scanning the oplog to determine where to place markers for truncation
2017-12-05T11:39:11.342+0000 I REPL     [conn1] ******
2017-12-05T11:39:11.376+0000 I INDEX    [conn1] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-05T11:39:11.376+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-05T11:39:11.378+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
2017-12-05T11:39:11.379+0000 I COMMAND  [conn1] setting featureCompatibilityVersion to 3.4
2017-12-05T11:39:11.380+0000 I REPL     [conn1] New replica set config in use: { _id: "rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "127.0.0.1:27018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "127.0.0.1:27019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "127.0.0.1:27020", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a26855fe4acd7d40a3b0158') } }
2017-12-05T11:39:11.380+0000 I REPL     [conn1] This node is 127.0.0.1:27018 in the config
2017-12-05T11:39:11.380+0000 I REPL     [conn1] transition to STARTUP2
2017-12-05T11:39:11.380+0000 I REPL     [conn1] Starting replication storage threads
2017-12-05T11:39:11.386+0000 I REPL     [ReplicationExecutor] Member 127.0.0.1:27020 is now in state STARTUP
2017-12-05T11:39:11.387+0000 I REPL     [ReplicationExecutor] Member 127.0.0.1:27019 is now in state STARTUP
2017-12-05T11:39:11.387+0000 I REPL     [conn1] Starting replication fetcher thread
2017-12-05T11:39:11.387+0000 I REPL     [conn1] Starting replication applier thread
2017-12-05T11:39:11.388+0000 I REPL     [conn1] Starting replication reporter thread
2017-12-05T11:39:11.389+0000 I REPL     [rsSync] transition to RECOVERING
2017-12-05T11:39:11.390+0000 I REPL     [rsSync] transition to SECONDARY
2017-12-05T11:39:11.393+0000 I -        [conn1] end connection 127.0.0.1:54426 (3 connections now open)
2017-12-05T11:39:13.330+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54440 #4 (3 connections now open)
2017-12-05T11:39:13.331+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54442 #5 (4 connections now open)
2017-12-05T11:39:13.331+0000 I -        [conn4] end connection 127.0.0.1:54440 (3 connections now open)
2017-12-05T11:39:13.332+0000 I -        [conn5] end connection 127.0.0.1:54442 (3 connections now open)
2017-12-05T11:39:13.394+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54452 #6 (3 connections now open)
2017-12-05T11:39:13.394+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54454 #7 (4 connections now open)
2017-12-05T11:39:13.394+0000 I NETWORK  [conn6] received client metadata from 127.0.0.1:54452 conn6: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:13.395+0000 I NETWORK  [conn7] received client metadata from 127.0.0.1:54454 conn7: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:13.396+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54456 #8 (5 connections now open)
2017-12-05T11:39:13.397+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54458 #9 (6 connections now open)
2017-12-05T11:39:13.397+0000 I NETWORK  [conn9] received client metadata from 127.0.0.1:54458 conn9: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:13.397+0000 I NETWORK  [conn8] received client metadata from 127.0.0.1:54456 conn8: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:15.222+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54460 #10 (7 connections now open)
2017-12-05T11:39:15.223+0000 I NETWORK  [conn10] received client metadata from 127.0.0.1:54460 conn10: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:16.388+0000 I REPL     [ReplicationExecutor] Member 127.0.0.1:27019 is now in state SECONDARY
2017-12-05T11:39:16.389+0000 I REPL     [ReplicationExecutor] Member 127.0.0.1:27020 is now in state SECONDARY
2017-12-05T11:39:18.399+0000 I -        [conn9] end connection 127.0.0.1:54458 (7 connections now open)
2017-12-05T11:39:18.399+0000 I -        [conn7] end connection 127.0.0.1:54454 (7 connections now open)
2017-12-05T11:39:22.270+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T11:39:22.271+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T11:39:22.272+0000 I REPL     [ReplicationExecutor] VoteRequester(term 0 dry run) received a yes vote from 127.0.0.1:27019; response message: { term: 0, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T11:39:22.273+0000 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-05T11:39:22.297+0000 I REPL     [ReplicationExecutor] VoteRequester(term 1) received a yes vote from 127.0.0.1:27019; response message: { term: 1, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T11:39:22.297+0000 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 1
2017-12-05T11:39:22.297+0000 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-05T11:39:22.298+0000 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-05T11:39:22.297+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending connection to host 127.0.0.1:27020 due to bad connection status; 0 connections to that host remain open
2017-12-05T11:39:22.298+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:39:22.299+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 127.0.0.1:27020, took 1ms (1 connections now open to 127.0.0.1:27020)
2017-12-05T11:39:22.299+0000 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-05T11:39:22.300+0000 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-05T11:39:23.398+0000 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-05T11:39:23.442+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54464 #11 (6 connections now open)
2017-12-05T11:39:23.442+0000 I NETWORK  [conn11] received client metadata from 127.0.0.1:54464 conn11: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:23.449+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54466 #12 (7 connections now open)
2017-12-05T11:39:23.450+0000 I NETWORK  [conn12] received client metadata from 127.0.0.1:54466 conn12: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:39:24.715+0000 I -        [conn10] end connection 127.0.0.1:54460 (7 connections now open)
2017-12-05T11:50:09.386+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2017-12-05T11:50:09.416+0000 I CONTROL  [initandlisten] MongoDB starting : pid=82 port=27018 dbpath=/data/27018/data 64-bit host=69c35c4e3456
2017-12-05T11:50:09.418+0000 I CONTROL  [initandlisten] db version v3.4.10
2017-12-05T11:50:09.418+0000 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-05T11:50:09.418+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-12-05T11:50:09.418+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-05T11:50:09.418+0000 I CONTROL  [initandlisten] modules: none
2017-12-05T11:50:09.419+0000 I CONTROL  [initandlisten] build environment:
2017-12-05T11:50:09.419+0000 I CONTROL  [initandlisten]     distmod: rhel70
2017-12-05T11:50:09.419+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-05T11:50:09.419+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-05T11:50:09.419+0000 I CONTROL  [initandlisten] options: { config: "/conf/27018.conf", net: { http: { enabled: false }, maxIncomingConnections: 300, port: 27018 }, processManagement: { fork: true, pidFilePath: "/data/27018/logs/mongod.pid" }, replication: { replSet: "rs" }, storage: { dbPath: "/data/27018/data" }, systemLog: { destination: "file", logAppend: true, path: "/data/27018/logs/mongod.log" } }
2017-12-05T11:50:09.421+0000 W -        [initandlisten] Detected unclean shutdown - /data/27018/data/mongod.lock is not empty.
2017-12-05T11:50:09.423+0000 I -        [initandlisten] Detected data files in /data/27018/data created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-12-05T11:50:09.424+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2017-12-05T11:50:09.425+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-05T11:50:16.745+0000 I STORAGE  [initandlisten] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-05T11:50:16.746+0000 I STORAGE  [initandlisten] The size storer reports that the oplog contains 7 records totaling to 660 bytes
2017-12-05T11:50:16.746+0000 I STORAGE  [initandlisten] Scanning the oplog to determine where to place markers for truncation
2017-12-05T11:50:16.767+0000 I CONTROL  [initandlisten] 
2017-12-05T11:50:16.768+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-05T11:50:16.768+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-05T11:50:16.768+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-05T11:50:16.769+0000 I CONTROL  [initandlisten] 
2017-12-05T11:50:16.777+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/27018/data/diagnostic.data'
2017-12-05T11:50:16.780+0000 I NETWORK  [thread1] waiting for connections on port 27018
2017-12-05T11:50:16.783+0000 W NETWORK  [replExecDBWorker-0] Failed to connect to 127.0.0.1:27020, in(checking socket for error after poll), reason: Connection refused
2017-12-05T11:50:16.783+0000 I REPL     [replExecDBWorker-0] New replica set config in use: { _id: "rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "127.0.0.1:27018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "127.0.0.1:27019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "127.0.0.1:27020", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a26855fe4acd7d40a3b0158') } }
2017-12-05T11:50:16.783+0000 I REPL     [replExecDBWorker-0] This node is 127.0.0.1:27018 in the config
2017-12-05T11:50:16.784+0000 I REPL     [replExecDBWorker-0] transition to STARTUP2
2017-12-05T11:50:16.784+0000 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-05T11:50:16.785+0000 I REPL     [replExecDBWorker-0] Starting replication fetcher thread
2017-12-05T11:50:16.786+0000 I REPL     [replExecDBWorker-0] Starting replication applier thread
2017-12-05T11:50:16.786+0000 I REPL     [replExecDBWorker-0] Starting replication reporter thread
2017-12-05T11:50:16.787+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27019
2017-12-05T11:50:16.787+0000 I REPL     [rsSync] transition to RECOVERING
2017-12-05T11:50:16.787+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:50:16.790+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to 127.0.0.1:27020 - HostUnreachable: Connection refused
2017-12-05T11:50:16.790+0000 I REPL     [rsSync] transition to SECONDARY
2017-12-05T11:50:16.790+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Dropping all pooled connections to 127.0.0.1:27020 due to failed operation on a connection
2017-12-05T11:50:16.791+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 127.0.0.1:27020; HostUnreachable: Connection refused
2017-12-05T11:50:16.791+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 127.0.0.1:27019, took 5ms (1 connections now open to 127.0.0.1:27019)
2017-12-05T11:50:16.792+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:50:16.793+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to 127.0.0.1:27020 - HostUnreachable: Connection refused
2017-12-05T11:50:16.793+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Dropping all pooled connections to 127.0.0.1:27020 due to failed operation on a connection
2017-12-05T11:50:16.794+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 127.0.0.1:27020; HostUnreachable: Connection refused
2017-12-05T11:50:16.794+0000 I REPL     [ReplicationExecutor] Member 127.0.0.1:27019 is now in state SECONDARY
2017-12-05T11:50:16.795+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:50:16.796+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to 127.0.0.1:27020 - HostUnreachable: Connection refused
2017-12-05T11:50:16.796+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Dropping all pooled connections to 127.0.0.1:27020 due to failed operation on a connection
2017-12-05T11:50:16.797+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 127.0.0.1:27020; HostUnreachable: Connection refused
2017-12-05T11:50:17.014+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2017-12-05T11:50:19.388+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54508 #1 (1 connection now open)
2017-12-05T11:50:19.388+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:54508 conn1: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:50:21.795+0000 I REPL     [ReplicationExecutor] Member 127.0.0.1:27019 is now in state PRIMARY
2017-12-05T11:50:21.797+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:50:21.798+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to 127.0.0.1:27020 - HostUnreachable: Connection refused
2017-12-05T11:50:21.798+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Dropping all pooled connections to 127.0.0.1:27020 due to failed operation on a connection
2017-12-05T11:50:21.798+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 127.0.0.1:27020; HostUnreachable: Connection refused
2017-12-05T11:50:21.798+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:50:21.799+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to 127.0.0.1:27020 - HostUnreachable: Connection refused
2017-12-05T11:50:21.799+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Dropping all pooled connections to 127.0.0.1:27020 due to failed operation on a connection
2017-12-05T11:50:21.799+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 127.0.0.1:27020; HostUnreachable: Connection refused
2017-12-05T11:50:21.800+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:50:21.800+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to 127.0.0.1:27020 - HostUnreachable: Connection refused
2017-12-05T11:50:21.800+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Dropping all pooled connections to 127.0.0.1:27020 due to failed operation on a connection
2017-12-05T11:50:21.801+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 127.0.0.1:27020; HostUnreachable: Connection refused
2017-12-05T11:50:24.944+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54544 #2 (2 connections now open)
2017-12-05T11:50:24.944+0000 I -        [conn2] end connection 127.0.0.1:54544 (2 connections now open)
2017-12-05T11:50:24.949+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54548 #3 (2 connections now open)
2017-12-05T11:50:24.950+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:54548 conn3: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:50:26.801+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to 127.0.0.1:27020
2017-12-05T11:50:26.803+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to 127.0.0.1:27020, took 2ms (1 connections now open to 127.0.0.1:27020)
2017-12-05T11:50:26.803+0000 I REPL     [ReplicationExecutor] Member 127.0.0.1:27020 is now in state SECONDARY
2017-12-05T11:50:27.791+0000 I REPL     [rsBackgroundSync] sync source candidate: 127.0.0.1:27019
2017-12-05T11:50:27.792+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to 127.0.0.1:27019
2017-12-05T11:50:27.794+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to 127.0.0.1:27019, took 2ms (1 connections now open to 127.0.0.1:27019)
2017-12-05T11:50:27.796+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to 127.0.0.1:27019
2017-12-05T11:50:27.798+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to 127.0.0.1:27019, took 2ms (2 connections now open to 127.0.0.1:27019)
2017-12-05T11:51:24.048+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54564 #4 (3 connections now open)
2017-12-05T11:51:24.050+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:54564 conn4: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:51:24.052+0000 I REPL     [conn4] replSetInitiate admin command received from client
2017-12-05T11:51:24.055+0000 I -        [conn4] end connection 127.0.0.1:54564 (3 connections now open)
2017-12-05T11:51:28.763+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:54566 #5 (3 connections now open)
2017-12-05T11:51:28.764+0000 I NETWORK  [conn5] received client metadata from 127.0.0.1:54566 conn5: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "CentOS Linux release 7.4.1708 (Core) ", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
2017-12-05T11:51:39.538+0000 I -        [conn5] end connection 127.0.0.1:54566 (3 connections now open)
2017-12-05T11:54:31.400+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to 127.0.0.1:27019
2017-12-05T11:54:31.402+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to 127.0.0.1:27019, took 2ms (3 connections now open to 127.0.0.1:27019)
2017-12-05T11:55:31.401+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host 127.0.0.1:27019 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T12:04:16.456+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to 127.0.0.1:27019
2017-12-05T12:04:16.458+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to 127.0.0.1:27019, took 2ms (3 connections now open to 127.0.0.1:27019)
2017-12-05T12:05:16.458+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host 127.0.0.1:27019 because the pool meets constraints; 2 connections to that host remain open
